### ISSUE TITLE
Include files refrenced in TextureArrayLoader in patch files mainfest

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#861] opened 2024-09-16 20:38 UTC
## Feature request 
Any local URLS referenced in the TextureArrayLoader op are included in the files manifest.

Then these are automatically packaged and downloaded with exports.

**Comment by TobyKLight** [comment] 2024-09-17 07:33
More info:
Files become untracked and linked to old patches when you are in a workflow where you are cloning your patch.

Regularly making a new clone of a patch to update release versions is very useful for showing a client "here's this weeks version".

**Comment by steam0r** [comment] 2024-09-17 07:46
i am closing this as a duplicate of cables-gl/cables_docs/issues/860

**Closed by steam0r** 2024-09-17 07:46 UTC
Labels: new
