### ISSUE TITLE
Mobile version bugs after the cables update

### ISSUE THREAD

**Issue by 873hz** [cables-gl/cables_docs#797] opened 2024-06-29 13:49 UTC
### Discussed in https://github.com/cables-gl/cables_docs/discussions/796

<div type='discussions-op-text'>

<sup>Originally posted by **873hz** June 26, 2024</sup>
I started to work on this patch in December and then paused for a while. 
Now I want to finish the project, but now I face some bugs that I haven't experienced previously. Maybe you can clarify if that is a bug because the patch required adaptability or if these are engine-related bugs. Sorry that the text is in Russian ( it makes everything a little bit unclear) but the issues are not content-related at all. They are mostly interaction-related. 

Issues:
1) The patch is crushing Safari for iOS users (iPhone 13)  on the second page (the page which is shown after the button click and animation of rotating cards and growing circles) when people start to scroll content down
2) For some Android users patch couldn't download textures (all ImageComposes show diagonal red lines instead of the images, I tried to reduce the resolution of the elements by a factor of 2 but it didn't help). On the other device, it even freezes the whole phone operative system after some interaction that I need to restart the phone (Nokia G10, checked with Chrome mobile and Opera. I guess this might be because of the weak hardware, but again, 6 months ago everything was running ok).

Patch link:
https://cables.gl/p/ue2g4O</div>

**Comment by pandrr** [comment] 2024-07-01 09:43
can't open the editor of the patch. hard to say what the problem is
please try updating all ops to the newest version, especially imagecompose/render to texture ops

**Comment by pandrr** [comment] 2024-07-08 08:37
duplicate of #796

please only create one issue or discussion in the future.

**Closed by pandrr** 2024-07-08 08:37 UTC
