### ISSUE TITLE
connection drawing drawing broken in subpatches

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#772] opened 2024-05-24 21:32 UTC
![image](https://github.com/cables-gl/cables_docs/assets/1138673/fcf978fd-b513-41c6-ab90-10bdf88ca66e)

**Comment by steam0r** [comment] 2024-05-27 07:56
can you provide an example patch and some context info on your browser/os/graphicscard, please?

https://cables.gl/browser

**Comment by wirmachenbunt** [comment] 2024-05-28 18:06
i discussed this with pandur, he knows where this is coming from. the op positions are way to high and cause funky rendering
this is just a reminder

**Comment by pandrr** [comment] 2024-05-28 19:29
i can't reproduce it really. please make an example

**Comment by pandrr** [comment] 2024-06-05 09:25
had another user give me an example... will not happen anymore, can be fixed by using ctrl/cmd+p "center ops in subpatch"

**Closed** 2024-06-24 10:17 UTC
Labels: bug, done

**Comment by wirmachenbunt** [comment] 2024-06-26 17:09
<img width="709" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1138673/5d3ad2f8-0aee-43f0-b0b1-e98368a78cbc">
seems still broken, happens in the first subpatch i made since weeks
and cmd + p, there is no center ops in subpatch

**Comment by wirmachenbunt** [comment] 2024-06-26 17:12
ah , in dev there is center ops.
anyway, the position of ops in subpatches in the public branch is still kaputt. or is this fix only on dev

**Comment by jnslxndr** [comment] 2024-06-26 18:43
If I may chime in, I can confirm the behaviour. Also, in dev Cmd+P > center ops on a broken subpatch only works if i first hit Cmd+S or save the op through the right sidebar op tree.

Browsers: Chrome current stable, Firefox current stable.

However, die fix appears to be not persistent. After reloading the patch containing the (nested or not) subpatches, the issue presents itself again.

**Comment by pandrr** [comment] 2024-06-27 07:23
fixed on dev.cables.gl, will be on cables.gl after next release.
