### ISSUE TITLE
SubPatch switch inputs can't be passed to Op switch inputs.

### ISSUE THREAD

**Issue by asford** [cables-gl/cables_docs#791] opened 2024-06-17 17:03 UTC
**Link to simple, reproducible example patch**

https://cables.gl/edit/5g2NVd

**Describe the bug**

*This is a concise bug report for part of https://github.com/cables-gl/cables_docs/discussions/773*

It is not possible to passthrough switch inputs from a SubPatch (where `string - switch` inputs accept strings and emit strings)
to a CustomOp (where `.inSwitch` inputs accept indexes and emit strings).

SubPatch `string - switch` ports work roughly as expected, they accept a switch in the UI, string value on the patch ,and emit a string string into the subpatch.

In contrast, an Op `inSwitch` creates two ports, the exposed switch (string valued) and the internal `.indexPort`.
The op exposes the string switch in the UI, but only exposes the integer-valued `.indexPort` on the patch field.
The patch-exposed `.indexPort` is `Number` typed and can't accept string values.

This makes it hard-to-impossible to pass switch values (which are used frequently) into a SubPatch,
because you need to perform manual string-to-index conversion within the patch.

**Proposed Fix**

Update Op `.inSwitch` ports to expose an object-typed port on the patch, which can accept *either* a string switch value or an integer switch index. This would allow immediate use of switch inputs in sub-patches. 

As an extended polish, update the SubPatch input-port-creation-via-drag interface to create a `string - switch` input in the subpatch matching the switch states of the contained op.

**How To Reproduce**
1. Open Editor
2. Create a SubPatch.
3. Add an Op with a switch input.
4. Add a `string - switch` input on the SubPatch.
5. *can't pass SubPatch string into Op*

**Comment by pandrr** [comment] 2024-07-08 08:39
duplicate of #773

please only create an issue or a discussion not both

**Closed by pandrr** 2024-07-08 08:39 UTC
Labels: bug
